# Generated by Django 5.2.10 on 2026-01-31 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["id"]},
        ),
    ]
