# Generated by Django 5.2.10 on 2026-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
