name: Deploy to Server

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/blackcat
          git pull origin develop
          docker compose down
          docker compose up -d --build
        EOF
